server:
  port: 8080

spring:
  application:
    name: opps-admin
  datasource:
    url: jdbc:mysql://localhost:3306/opspanel?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.opspanel: info

security:
  jwt:
    secret: "e7v6f9d3a1b0c4x8z9y2r7t5u6p3q0m1n5w8e2r4t6y7u8i9o0p1q2w3e4r5t6"
    access-token-expiration-ms: 600000       # 10 minutes
    refresh-token-expiration-ms: 3600000     # 1 hour
    token-prefix: Bearer
    header: Authorization